config/routes.rb
Rails.application.routes.draw do
  resources :clients do 
    resources :web_properties
    resources :contacts
  end
  resources :contacts do
    resources :clients
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :web_properties, dependent: :destroy
  has_and_belongs_to_many :contacts
  validates :name, presence: true, uniqueness: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_and_belongs_to_many :clients
end

app/models/web_property.rb
class WebProperty < ApplicationRecord
  belongs_to :client
  validates :name, presence: true
  validates :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def get_contact
      @contact = Contact.find(params[:contact_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :address)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def get_client
      @client = Client.find(params[:client_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :address)
    end
end

app/controllers/web_properties_controller.rb
class WebPropertiesController < ApplicationController
  before_action :get_client
  before_action :set_web_property, only: %i[ show edit update destroy ]

  # GET /web_properties or /web_properties.json
  def index
    @web_properties = @client.web_properties
  end

  # GET /web_properties/1 or /web_properties/1.json
  def show
  end

  # GET /web_properties/new
  def new
    @web_property = @client.web_properties.build
  end

  # GET /web_properties/1/edit
  def edit
  end

  # POST /web_properties or /web_properties.json
  def create
    @web_property = @client.web_properties.build(web_property_params)

    respond_to do |format|
      if @web_property.save
        format.html { redirect_to @client, notice: "Web property was successfully created." }
        format.json { render :show, status: :created, location: @web_property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @web_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /web_properties/1 or /web_properties/1.json
  def update
    respond_to do |format|
      if @web_property.update(web_property_params)
        format.html { redirect_to client_url(@client), notice: "Web property was successfully updated." }
        format.json { render :show, status: :ok, location: @web_property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @web_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /web_properties/1 or /web_properties/1.json
  def destroy
    if @web_property.destroy
      msg = "Property was successfully deleted."
      respond_to do |format|
        format.html { redirect_to client_path(@client), notice: msg }
        format.json { head :no_content }
      end
    else
      msg = "There was an issue deleting the property."
      respond_to do |format|
        format.html { redirect_to client_path(@client), alert: msg }
        format.json { head :no_content }
      end
    end

  end

  private
    def get_client
      @client = Client.find(params[:client_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_web_property
      @web_property = @client.web_properties.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def web_property_params
      params.require(:web_property).permit(:name, :url, :client_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/web_properties_helper.rb
module WebPropertiesHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Name:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= client.address %>
  </p>

</div>

app/views/clients/_contact.html.erb
<li class="list-group-item">
  <%= contact.name %>:
  <div class = "card-nav contact_admin">
    <%= link_to edit_client_contact_path(@client, contact), class: 'btn btn-secondary btn-sm' do %>
      <i class='fas fa-edit'></i> Edit
    <% end %>
    <%= button_to client_contact_path(@client, contact), 
      method: :delete, 
      form:{ 
        data: { turbo_confirm: "Are you sure you want to delete the contact: #{contact.name}?"  }
      },
      class: 'btn btn-secondary btn-sm' do
    %>
      <i class='fas fa-trash'></i> Delete
    <% end %>
  </div>
</li>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_area :address, :class => "form-control" %>
  </div>

  <div class="mb2">
    <%= form.button :submit, :class => "btn btn-primary" do %>
      <span class="fas fa-check"></span> Save
    <% end %>

    <%= link_to @client, :class => "btn btn-danger" do  %>
      <span class="fas fa-ban"></span> Cancel
    <% end %> 
  </div>
<% end %>

app/views/clients/_web_property.html.erb
<li class="list-group-item">
  <%= web_property.name %>:
  <%= link_to web_property.url, web_property.url %>
  <div class = "card-nav web-properties_admin">
    <%= link_to edit_client_web_property_path(web_property.client, web_property), class: 'btn btn-secondary btn-sm' do %>
      <i class='fas fa-edit'></i> Edit
    <% end %>
    <%= button_to client_web_property_path(web_property.client, web_property), 
      method: :delete, 
      form:{ 
        data: { turbo_confirm: "Are you sure you want to delete the property: #{web_property.name}?"  }
      },
      class: 'btn btn-secondary btn-sm' do
    %>
      <i class='fas fa-trash'></i> Delete
    <% end %>
  </div>
</li>

app/views/clients/edit.html.erb
<div class="card-header d-flex justify-content-between">
  <h1>Editing <%= link_to @client.name, @client %></h1>
  <div class="card-nav">
    <%= link_to clients_path, :class => "btn btn-secondary" do  %>
      <span class="fas fa-arrow-left"></span> Back to Clients
    <% end %> 
  </div>
</div>

<div class="card-body">
  <%= render "form", client: @client %>
</div>

app/views/clients/index.html.erb
<div class="card-header">
  <h1>Clients</h1>
  <div class="card-nav">
    <%= link_to new_client_path, :class => "btn btn-secondary" do  %>
      <span class="fas fa-plus"></span> Create a New Client
    <% end %> 
  </div>
</div>

<ul id="clients" class="list-group">
  <% @clients.each do |client| %>
    <li class="list-group-item">
      <%= link_to client.name, client %>
    </li>
  <% end %>
</ul>

app/views/clients/new.html.erb
<div class="card-header">
  <h1>New client</h1>
  <div class="card-nav">
    <%= link_to clients_path, :class => "btn btn-secondary" do  %>
      <span class="fas fa-arrow-left"></span> Back to Clients
    <% end %> 
  </div>
</div>

<div class="card-body">
  <%= render "form", client: @client %>
</div>

app/views/clients/show.html.erb
<div class="card-header"> 
  <h1><%= @client.name %></h1>
  <div class="card-nav">
    <%= link_to clients_path, :class => "btn btn-secondary" do  %>
      <span class="fas fa-arrow-left"></span> Back to Clients
    <% end %> 
  </div>
</div>

<div class="card-body client">
  <h2>Address</h2>
  <p><%= @client.address.empty? ? "No Address on File" : @client.address %></p>

  <div class="client-web-properties">
    <h2>Properties</h2>
    <% if @client.web_properties.empty? %>
      <p>No properties have been added yet.</p>
    <% else %>
      <ul class="web-properties list-group">
        <%= render partial: "web_property", collection: @client.web_properties, object: @client %>
      </ul>
    <% end %>
    <%= link_to new_client_web_property_url(@client), :class => "btn btn-primary" do %>
      <span class="fas fa-plus"></span> Add New Property</span>
    <% end %>
  </div>

  <div class="client-contacts">
    <h2>Contacts</h2>
    <% if @client.contacts.empty? %>
      <p>No contacts have been added yet.</p>
    <% else %>
      <ul class="web-properties list-group">
        <%= render partial: "contact", collection: @client.contacts%>
      </ul>
    <% end %>
    <%= link_to new_contact_url, :class => "btn btn-primary" do %>
      <span class="fas fa-plus"></span> Add New Contact</span>
    <% end %>
  </div>
</div>
<div class="card-footer">
  <div class="card-nav">
  <%= link_to edit_client_path(@client), :class => "btn btn-secondary" do  %>
    <span class="fas fa-edit"></span> Edit this client
  <% end %> 
    <%= button_to @client, 
      :class => "btn btn-secondary",
      method: :delete, 
      form: { 
        data: { turbo_confirm: "Are you sure you want to delete this client?"  }
      } do %>
      <span class="fas fa-trash"></span> Delete this Client
    <% end %>
  </div>
</div>

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Client:</strong>
    <%= contact.client_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= contact.name %>
  </p>

  <p>
    <strong>Street:</strong>
    <%= contact.street %>
  </p>

  <p>
    <strong>Secondary address:</strong>
    <%= contact.secondary_address %>
  </p>

  <p>
    <strong>City:</strong>
    <%= contact.city %>
  </p>

  <p>
    <strong>Zip:</strong>
    <%= contact.zip %>
  </p>

  <p>
    <strong>State:</strong>
    <%= contact.state %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= contact.country %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= contact.notes %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Contact Name" %>
    <%= form.text_field :name, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :street, "Street Address" %>
    <%= form.text_field :street, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :secondary_address %>
    <%= form.text_field :secondary_address, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :zip %>
    <%= form.text_field :zip, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :state %>
    <%= form.text_field :state, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :country %>
    <%= form.text_field :country, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :notes %>
    <%= form.text_area :notes, :class => "form-control" %>
  </div>

  <div class="mb2">
    <%= form.button :submit, :class => "btn btn-primary" do %>
      <span class="fas fa-check"></span> Save
    <% end %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contacts</h1>

<div id="contacts">
  <% @contacts.each do |contact| %>
    <%= render contact %>
    <p>
      <%= link_to "Show this contact", contact %>
    </p>
  <% end %>
</div>

<%= link_to "New contact", new_contact_path %>

app/views/contacts/new.html.erb
<div class="card-header">
  <h1>New contact</h1>

  <div class="card-body">
    <%= render "form", contact: @contact %>
    <%= link_to "Back to contacts", contacts_path %>
  </div>
</div>

app/views/contacts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>

  <%= button_to "Destroy this contact", @contact, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Armadillo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/e324fb2274.js" data-mutate-approach="sync" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-dark">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
          <% if notice %>
            <div class="alert alert-primary mt-5" role="alert" id="notice"><%= notice %></div>
          <% end %>
          <% if alert %>
            <div class="alert alert-danger mt-5" role="alert" id="notice"><%= alert %></div>
          <% end %>
          <div class="card mt-5">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/web_properties/_form.html.erb
<%= form_with(model: [@client, web_property] ) do |form| %>
  <% if web_property.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(web_property.errors.count, "error") %> prohibited this web_property from being saved:</h2>

      <ul>
        <% web_property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, :class => "form-control" %>
  </div>

  <div class="mb2">
    <%= form.button :submit, :class => "btn btn-primary" do %>
      <span class="fas fa-check"></span> Save
    <% end %>

    <%= link_to @client, :class => "btn btn-danger" do  %>
      <span class="fas fa-ban"></span> Cancel
    <% end %> 
  </div>
<% end %>

app/views/web_properties/_web_property.html.erb
<div id="<%= dom_id web_property %>">
  <p>
    <strong>Name:</strong>
    <%= web_property.name %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= web_property.url %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= web_property.client_id %>
  </p>

</div>

app/views/web_properties/edit.html.erb
<div class="card-header">
  <h1>Editing web property</h1>
  <div class="card-nav">
    <%= link_to client_path(@client), :class => "btn btn-secondary" do %>
      <span class="fas fa-arrow-left"></span> Back to <%= @client.name %>
    <% end %>
  </div>
</div>

<div class="card-body">
  <%= render "form", web_property: @web_property %>
</div>

app/views/web_properties/index.html.erb
<div class="card-header d-flex justify-content-between">
  <h1>Web properties for <% @client.name %></h1>
</div>

<ul id="web_properties" class="list-group">
  <% @web_properties.each do |web_property| %>
    <li class="list-group-item">
      <%= link_to web_property.name, web_property.url %>
    </li>
  <% end %>
</div>

app/views/web_properties/new.html.erb
<div class="card-header d-flex justify-content-between">
  <h1>New web property</h1>
  <%= link_to "Back to #{@client.name}", @client %>
</div>

<div class="card-body">
  <%= render "form", web_property: @web_property %>
</div>

app/views/web_properties/show.html.erb
<div class="card-header"> 
  <h1><%= @web_property.name %></h1>
  <div class="card-nav">
    <%= link_to clients_path, :class => "btn btn-secondary" do  %>
      <span class="fas fa-arrow-left"></span> Back to <%= @client.name %>
    <% end %> 
  </div>
</div>

<div class="card-body web-property">
  <%= render @web_property %>
</div>

<div class="card-footer">
  <div class="card-nav">
  <%= link_to edit_client_web_property_path(@client, @web_property), :class => "btn btn-secondary" do  %>
    <span class="fas fa-edit"></span> Edit this Property
  <% end %> 
    <%= button_to client_web_property_path(@client, @web_property),
      :class => "btn btn-secondary",
      method: :delete, 
      form: { 
        data: { turbo_confirm: "Are you sure you want to delete this property, #{ @web_property.name }?"  }
      } do %>
      <span class="fas fa-trash"></span> Delete this Property
    <% end %>
  </div>
</div>